/*
https://programmers.co.kr/learn/courses/30/lessons/59045
Oracle로 풂.
*/

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O LEFT OUTER JOIN ANIMAL_INS I
ON (O.ANIMAL_ID = I.ANIMAL_ID)
WHERE O.DATETIME is not null
AND O.SEX_UPON_OUTCOME != I.SEX_UPON_INTAKE
ORDER BY ANIMAL_ID;