/*
https://programmers.co.kr/learn/courses/30/lessons/59411
Oracle로 풂.
*/

SELECT DISTINCT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE I.ANIMAL_ID = O.ANIMAL_ID
AND I.DATETIME is not null
AND (O.DATETIME - I.DATETIME) > 0
ORDER BY (O.DATETIME - I.DATETIME) desc FETCH FIRST 2 ROWS ONLY;